name: PR Checks

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-lint:
    name: Build and Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        run: npm run lint
        
      - name: Build
        run: npm run build
        
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            build
            node_modules
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build- 